name: CI/CD Hotel Ops Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: admin
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U admin"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      kafka:
        image: confluentinc/cp-kafka:7.6.0
        ports:
          - 9092:9092
        options: >-
          --health-cmd "echo 'Kafka ready'"
          --health-interval 10s
          --health-retries 5
        depends-on:
          - postgres

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend deps
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          npm run test --if-present

      - name: Build frontend
        run: |
          cd frontend/react-app
          npm ci
          npm run build
